# k8s base for web-frontend — Phase 2
# TODO: add deployment.yaml, service.yaml, serviceaccount.yaml, ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
# resources:
#   - deployment.yaml
#   - service.yaml
#   - serviceaccount.yaml
#   - ingress.yaml
